### ISSUE TITLE
FailedDiscoveryCheck: error 403

### ISSUE THREAD

**Issue by nerzhul** [kubernetes-sigs/prometheus-adapter#227]
Hello, i'm deploying the adapter using kube-prometheus project but i'm unable to use metrics because the apiserver is broken.

Here is the description:
```
Status:
  Conditions:
    Last Transition Time:  2019-08-06T15:24:54Z
    Message:               failing or missing response from https://100.100.37.221:443: bad status from https://100.100.37.221:443: 403
    Reason:                FailedDiscoveryCheck
    Status:                False
    Type:                  Available
Events:                    <none>
```
The pod is running like a charm:

```
prometheus-adapter-7f9ccd447c-gpfvd    1/1     Running   0          8d
```
The service is here:

```
prometheus-adapter    ClusterIP   100.100.37.221    <none>        443/TCP             11d
```

And here is the endpoints
```
prometheus-adapter    100.100.132.8:6443                                                  11d
```

There is no interesting logs on the pod, how can i debug this issue ?

Thanks in advance

**Comment by tfluehmann** [comment]
I am currently facing the same issue, without any clue how to fix it.

**Comment by kushalarya** [comment]
@tfluehmann @nerzhul 
In file `/etc/kubernetes/manifests/kube-apiserver.yaml`, add ClusterIP of prometheus-adapter in `no_proxy `

**Comment by tfluehmann** [comment]
You're the man @kushalarya ! Adding the prometheus-adapter ClusterIP fixed it for me :100: 
Haven't though about the proxy and the service address so far.

**Comment by vishwasmittal** [comment]
I came across this issue with the following log:
```
k8s.io/apiserver/pkg/server/dynamiccertificates/configmap_cafile_content.go:209: Failed to list *v1.ConfigMap: configmaps "extension-apiserver-authentication" is forbidden: User "system:serviceaccount:custom-metrics:custom-metrics-apiserver" cannot list resource "configmaps" in API group "" in the namespace "kube-system"
```

Turns out the `system:serviceaccount:custom-metrics:custom-metrics-apiserver` couldn't not access `extension-apiserver-authentication` config map required to verify the request headers.

To fix this, add `configmaps` to `resources` in `k8s-prometheus-adapter/deploy/manifests/custom-metrics-resource-reader-cluster-role.yaml` and apply it.

Your `custom-metrics-resource-reader-cluster-role.yaml` file should look like:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: custom-metrics-resource-reader
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - nodes/stats
  - configmaps
  verbs:
  - get
  - list
  - watch
```


Checkout https://github.com/kubernetes-sigs/apiserver-builder-alpha/blob/master/docs/concepts/auth.md#requestheader-authentication for more details.
