### ISSUE TITLE
Adapter not connecting to Prometheus

### ISSUE THREAD

**Issue by param3sh** [kubernetes-sigs/prometheus-adapter#298]
Hi, I have installed prometheus-adapter through helm (helm install a-2-4-0 stable/prometheus-adapter --set prometheus.url=http://prome-0-1-4-prometheus --set prometheus.port=80), i am getting empty set of resource when i do "kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1". i have checked the adapter pod logs and did not see any logs related to adapter and prometheus connections. there are many log entries like (1 wrap.go:47] GET /apis/custom.metrics.k8s.io/v1beta1). 

I have checked prometheus URL, and i am able to get metrics and their values. 

can you please help me with it.

**Comment by arvin6msd** [comment]
I have the same problem, Did you manage to solve this?

Log from adapter:
`I0714 14:20:24.248426       1 wrap.go:47] GET /apis/custom.metrics.k8s.io/v1beta1?timeout=32s: (237.548µs) 200 [kubectl/v1.16.0 (linux/amd64) kubernetes/2bd9643 192.168.94.246:45320]
E0714 14:20:24.949209       1 provider.go:209] unable to update list of all metrics: unable to fetch metrics for query "{namespace!=\"\",__name__!~\"^container_.*\"}": bad_response: unknown response code 404
I0714 14:20:24.963950       1 wrap.go:47] GET /healthz: (88.96`

**Comment by bwkerbow** [comment]
Im having the same problem. did yall manage to solve it?

**Comment by rishi1111** [comment]
+1 same issue any luck guys

**Comment by rishi1111** [comment]
I could resolve this issue by setting
prometheus.path = "/prometheus" (change as per your env)

**Comment by bwkerbow** [comment]
Nice @rishi1111.

I solved as well, in my case the issue is that I specieied the prometehus url to be the cname of my prometehus server, and there was an authorization issue there. To get around that, I just used the automatically generated DNS record for the k8s service (https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#services) that the CNAMEs ingress was pointing to.

**Comment by robin-coac** [comment]
I am also getting empty resource list. I think it's due to this log-message in my prom adapter. 

E0905 11:26:21.387825       1 provider.go:229] unable to update list of all metrics: unable to fetch metrics for query "{namespace!=\"\", service!=\"\" }": Get "http://prometheus-server-kube-pro-prometheus.flux-test.svc:9090/api/v1/series?match%5B%5D=%7Bnamespace%21%3D%22%22%2C+service%21%3D%22%22+%7D&start=1693913121.383": read tcp 10.42.1.245:44828->10.43.131.216:9090: read: connection reset by peer

Could anyone help ?
