### ISSUE TITLE
resources shows empty ocassionally at "kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1" endpoint

### ISSUE THREAD

**Issue by navathag** [kubernetes-sigs/prometheus-adapter#325]
i have my relist interval set to same as the prometheus scrape interval i still face the issue(metrics keep disappearing) sometimes i get the metrics while sometimes i get empty resources at "kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1
{"kind":"APIResourceList","apiVersion":"v1","groupVersion":"custom.metrics.k8s.io/v1beta1","resources":[]}"

```
`custom-metrics-apiserver-deployment ` config:
        args:
        - --secure-port=6443
        - --tls-cert-file=/var/run/serving-cert/serving.crt
        - --tls-private-key-file=/var/run/serving-cert/serving.key
        - --logtostderr=true
        - --prometheus-url=http://prom-global-svc.monitor:9090/prom/global
        - --metrics-relist-interval=15s
        - --v=10
        - --config=/etc/adapter/config.yaml
```
And prometheus config:

```
global:
  evaluation_interval: 1m
  scrape_interval: 15s
  scrape_timeout: 5s
```
Could you please suggest me on this

**Comment by dobesv** [comment]
Have you tried setting your relist interval to a much larger value than prometheus' scrape interval?  Maybe 150s ?

**Comment by navathag** [comment]
@dobesv what would be the best value for this relist interval? and i am passing multiple metrics for adapter so do i have to increase the relist interval everytime i increase the metrics through config for adapter?

**Comment by dobesv** [comment]
The "relist interval" refers to the time range used to discover metrics, so the custom metrics will only consider metrics that have a sample available within that time.

I think the concern with setting the interval close to the scrape interval of prometheus is that if prometheus runs into any delays with scraping then there might not be any data available within that interval at all.

With a longer interval, you reduce the chances of that happening.

I guess the downside of a longer interval is that the metrics server will use more memory and CPU processing data points that might be related to pods that are no longer running, so setting it to hours would waste resources.  Also I wonder if a long interval can mean it will take a long time for a pod's data to be available from the metrics server.

So that's why I thought setting to a few minutes would be reasonable - long enough to ensure prometheus has a chance to scrape all the pods (even ones that fail to respond occasionally, or respond slowly), but not so long that there will be a ton of extra data being processed at the same time.

All of that said, I'm not an expert on how this prometheus adapter works.  I only discovered the above today while investigating an autoscaling issue and trying to figure what might be the cause.  I realized my relist interval was only double the scrape interval, so if a target failed to respond just once, it might not have any metrics for the next period.

It's also possible that I'm confused about how the relist interval works...

**Comment by navathag** [comment]
@dobesv thankyou for the response. As you mentioned My concern of setting relist interval long is if it take a long time for a pod's data to be available from the metrics server. Will try with interval set to more than scrape interval and observe for a while.
And also sometime when i don't see metrics at api end point i checked for adapter logs and error message says 

`I1030 20:11:13.573075       1 series_registry.go:156] metric pods/tomcat_threads_busy_threads(namespaced) not registered
I1030 20:11:13.573180       1 httplog.go:90] GET /apis/custom.metrics.k8s.io/v1beta1/namespaces/astra/pods/%2A/tomcat_threads_busy_threads?labelSelector=app%3Dcart%2Cversion%3D1c: (20.435422ms) 404 [hyperkube/v1.16.8 (linux/amd64) kubernetes/ec6eb11/system:serviceaccount:kube-system:horizontal-pod-autoscaler 172.18.5.194:40504]`

even when i see metrics at prometheus side. Please let me know if you know anything on this. Other thing i observed is one metrics appear at the endpoint once and later other metrics showup, sometimetimes both metrics show up. Let me know if this is related to relist interval? if so i will try out multiple relist interval and observe the output. Thanks in advance
