### ISSUE TITLE
Why the result of rate is different with prometheus?

### ISSUE THREAD

**Issue by muqp** [kubernetes-sigs/prometheus-adapter#360]
I want to get the rate of pod's receive bytes.The metricsquery is rate(<<.Series>>[5m]).But the result is different with prometheus.The query is rate(container_network_receive_bytes_total[5m]).There is config of primetheus adapter:

…
- seriesQuery: '{__name__=~"^container_network_receive_.*",container_name="POD",namespace!="",pod_name!=""}'
  seriesFilters: []
  resources:
    overrides:
      namespace:
        resource: namespace
      pod_name:
        resource: pod
  name:
    matches: ^(.*)(network_receive_bytes)(_total)$
    as: "${2}"
  metricsQuery: rate(<<.Series>>[5m])
…

**Comment by muqp** [comment]
The result is
![image](https://user-images.githubusercontent.com/52477868/104869587-60864e80-5981-11eb-8c4d-8da56ce99349.png)
What the meaning of 'm'?

**Comment by dgrisonnet** [comment]
The prometheus-adapter API uses quantities with SI system to represent metrics value instead of decimal points as in Prometheus which is why you are noticing a difference here. The `m ` suffix stands for milli-unit. You can find more information about it in the doc: https://github.com/DirectXMan12/k8s-prometheus-adapter/blob/master/docs/walkthrough.md#quantity-values

**Comment by muqp** [comment]
> The metrics API uses quantities with SI system to represent metrics value instead of decimal points as in Prometheus which is why you are noticing a difference here. The `m ` suffix stands for milli-unit, you can find more information about it in the doc: https://github.com/DirectXMan12/k8s-prometheus-adapter/blob/master/docs/walkthrough.md#quantity-values

I know.I found the result of irate is same with prometheus.
