### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by frederiksf** [kubernetes-sigs/prometheus-adapter#466]
Does the prometheus adapter implement support for windows workloads (node and pods). After deploying the prometheus-adapter instead of metric-server the command kubectl top node only gives metrics back for linux and not for our windows and. For pods the same story. Linux pod metrics ok but not available for Windows.

**Comment by frederiksf** [comment]
Anyone

**Comment by ErwinRebergen** [comment]
Same issue here. Anyone?

**Comment by dgrisonnet** [comment]
The kube-prometheus project has a windows specific configuration for prometheus-adapter: https://github.com/prometheus-operator/kube-prometheus/blob/main/manifests/prometheus-adapter-configMap.yaml. It requires to run https://github.com/prometheus-community/windows_exporter to get metrics from windows nodes. However, it is not possible today to get metrics from windows pods since kubernetes relies on cadvisor which doesn't support windows containers.
