### ISSUE TITLE
Window and default queries seem inconsistent

### ISSUE THREAD

**Issue by markusthoemmes** [kubernetes-sigs/prometheus-adapter#555]
The default queries use an `irate` window over 4m, see https://github.com/kubernetes-sigs/prometheus-adapter/blob/307795482f68fd68bb9b56fc117447ecc980ba58/deploy/manifests/config-map.yaml#L10

The default window is set to 5m, see https://github.com/kubernetes-sigs/prometheus-adapter/blob/307795482f68fd68bb9b56fc117447ecc980ba58/deploy/manifests/config-map.yaml#L45

The comment on the window config states that the two should match, so now I'm bamboozled. Am I missing something?

**Comment by olivierlemasle** [comment]
@markusthoemmes I guess you're referring to this comment:

https://github.com/kubernetes-sigs/prometheus-adapter/blob/c893b1140c108029dc3f865ce15cb5b7b9177f95/pkg/config/config.go#L91-L92

On the contrary, the README recommends having a discovery interval (= window) **at least as large** as the collection interval:

https://github.com/kubernetes-sigs/prometheus-adapter/blob/307795482f68fd68bb9b56fc117447ecc980ba58/README.md?plain=1#L207-L216

I ***think*** that the README is correct here, and the comment should be updated.

Do you agree @dgrisonnet?

/triage accepted

**Comment by dgrisonnet** [comment]
I forgot that this was even configurable. Looking at the code again, it doesn't seem to be doing anything except adding the window value from the config to the returned metric object.

The window field returned by prometheus should always be equal to the query range since it is meant to reflect the interval of timeseries used to compute the metric value: https://github.com/kubernetes/metrics/blob/v0.26.0/pkg/apis/metrics/types.go#L73-L76.
That means that the current configuration should be updated to set the window to `4m` in order to properly reflect the interval in the query. That said this is not very accurate since and irate only take the last 2 datapoints so in practice and in most cases the a more accurate window would be the scrape interval, but we should always consider the worst scenario since Prometheus doesn't tell us which datapoints were used. 

Going back to the README, it is quite confusing, but I don't think it refers to the actual window in the configuration but rather the rate interval in the queries. A general guide to set the discovery interval properly would be:
https://www.robustperception.io/what-range-should-i-use-with-rate/.

**Comment by markusthoemmes** [comment]
An interesting side-effect of `window` seems to be that it triggers the HPA to only consider the metric once the window has passed (this is anecdotal, I haven't yet gone and scouted the HPA code for a smoking gun here). The behavior observed was that `kubectl top pods` returned accurate CPU metrics in ~prometheus' scrape interval while the HPA was reporting"did not receive metrics for any ready pods" until the 5m window was passed.

Could be a feature though to not take premature values, I guess 😅  

Agree though that in the above example, we probably want to change the window to 4m to be consistent with the docs.

**Comment by markusthoemmes** [comment]
I understood what you meant with the "not very accurate, takes only 2 datapoints and in most cases the window is the scrape interval".

Which makes me wonder: What's the worst-case behavior if we keep the queries running on 4m to be "safe" as explained in the article but reduce the window to scrape-interval? I guess the HPA would not ignore pods after the scrape-interval but if the query fails, it'd bark at not being able to find metrics, which may be fine?

**Comment by dgrisonnet** [comment]
I am not familiar enough with the HPA code to be able to give you an accurate answer. From the piece of code you shared I would guess that having a large windows may result in reusing stale metrics and not being very accurate whereas having a smaller window might result in errors. But I might not be understanding that correctly, it might be worth checking because if that was the case I would be more inclined to choose a smaller window.

**Comment by james-callahan** [comment]
@markusthoemmes I also noticed the 4m vs 5m difference.

It's not clear from the above discussion if they should be made equal or not.
